### PR TITLE
Add adro.rocks

### PR DESCRIPTION
**Pull request by adrorocker**
Description here.

- [x] This is adding a new web site to BuiltWithJigsaw
- [ ] This is not a new web site, but something else 

If this is adding a new web site:

- [x] I have created a screenshot
- [x] The screenshot is sized 380x210
- [x] The screenshot is saved with PNG-8, not PNG-24, and I've run it through an image optimization tool like [ImageOptim](https://imageoptim.com/mac)
- [x] I saved the screenshot with the same filename as my site's `.md` file, but as a `.png` instead
- [x] I saved the screenshot in the `/source/assets/images/sites` directory
- [x] I built the site locally to ensure it looks right

### CODE REVIEW

**Comment by mattstauffer** [comment]
Hey @adrorocker, could you take a look at the format of the other screenshots on the live site and make a screenshot like those? No browser Chrome, no shadow.

Thanks!

**Comment by adrorocker** [comment]
Hey @mattstauffer sure thing, thanks for the feedback.

**Comment by adrorocker** [comment]
@mattstauffer Can you review this PR again I replace the images with the required format.

Thanks in advance 🤘🏽

**Comment by bakerkretzmar** [comment]
@adrorocker is the GitHub repo private? That link 404s for me.

**Comment by adrorocker** [comment]
@bakerkretzmar You are completely right, my bad. I removed the repo link. 

Thanks for looking at this.

**Pull request merged**
