### PR TITLE
Add libresign.coop

### PR DESCRIPTION
**Pull request by vitormattos**
```yaml
title: "LibreSign: Digital document signer"
authors: [Vitor Mattos]
url: https://libresign.coop
added: 2024-08-31
types: [project]
repo: https://github.com/LibreSign/site
usedGenerator: true
```

Description here.

- [x] This is adding a new web site to BuiltWithJigsaw
- [ ] This is not a new web site, but something else 

If this is adding a new web site:

- [x] I have created a screenshot
- [x] The screenshot is sized 380x210
- [x] The screenshot is saved with PNG-8, not PNG-24, and I've run it through an image optimization tool like [ImageOptim](https://imageoptim.com/mac)
- [x] I saved the screenshot with the same filename as my site's `.md` file, but as a `.png` instead
- [x] I saved the screenshot in the `/source/assets/images/sites` directory
- [x] I built the site locally to ensure it looks right

### CODE REVIEW

**Comment by mateusjunges** [comment]
Hey @vitormattos https://libresign.coop does not load for me. Is it still a thing?

**Comment by vitormattos** [comment]
Yes!
If you also wish to know more and contribute with LibreSign, I will like a lot! :-D
Follow the repository of site: https://github.com/libresign/site
And follow the repository of LibreSign: https://github.com/LibreSign/libresign/

**Comment by vitormattos** [comment]
I will soon create another website in Jigsaw for a disaster-resilient infrastructure project without using big tech solutions, made using only free software.

**Comment by mateusjunges** [comment]
Ok, I'm merging this one as I managed to load the site now. Thanks!

**Pull request merged**
